# Generated by Django 5.0.6 on 2024-07-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_remove_order_products_delete_products_delete_order'),
        ('products', '0005_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='products.products')),
            ],
        ),
    ]
