# Generated by Django 5.0.6 on 2024-07-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_product',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_products',
            field=models.ManyToManyField(related_name='recommended_for_product', to='products.products'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to='products.products'),
        ),
    ]
