# Generated by Django 5.0.6 on 2024-07-06 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Deactivated')], default='NO', max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('EL', 'Electronics'), ('HM', 'Home & Kitchen'), ('BT', 'Beauty & Personal Care'), ('SP', 'Sports & Outdoors'), ('OF', 'Office Supplies'), ('HG', 'Health & Wellness'), ('BK', 'Books & Media'), ('TS', 'Toys & Games'), ('JW', 'Jewelry & Accessories'), ('FD', 'Food & Beverages'), ('NO', 'None')], max_length=2)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
