# Generated by Django 5.0.6 on 2024-07-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('DA', 'Deactivated')], default='NO', max_length=2),
        ),
    ]
