# Generated by Django 5.0.6 on 2024-07-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('HM', 'Home & Kitchen'), ('BT', 'Beauty & Personal Care'), ('SP', 'Sports & Outdoors'), ('OF', 'Office Supplies'), ('HG', 'Health & Wellness'), ('BK', 'Books & Media'), ('TS', 'Toys & Games'), ('JW', 'Jewelry & Accessories'), ('FD', 'Food & Beverages'), ('NO', 'None')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Deactivated')], default='D', max_length=1),
        ),
    ]
